### ISSUE TITLE
Week 1 - First implementation

### ISSUE THREAD

**Issue by jamiamikko** [jamiamikko/FallWatch#5]
Start developing the application.

- Layout
- Basic features
- Shared preferences

**Comment by jamiamikko** [comment]
- Layout started,
- Register class done
- Sidebar class started

**Comment by roopevi** [comment]
First implementation ready. 

- Layout and color palette
- Registeration working (shared preferences)
- Internal gravity sensor implemented (we might change it to accelerometer)
